FROM php:8.2-apache      

COPY index.php /var/www/html/

EXPOSE 80


# php:8.2-apache → image officielle avec Apache + PHP déjà prêts

# COPY → place ta page dans le dossier web d’Apache

# EXPOSE 80 → Apache écoute sur le port 80 dans le conteneur
