# php:8.2-apache → image officielle avec Apache + PHP déjà prêts
FROM php:8.2-apache      

# COPY → place ta page dans le dossier web d’Apache
WORKDIR /app

# Définit le répertoire de travail dans le conteneur
COPY index.php /var/www/html/

# EXPOSE 80 → Apache écoute sur le port 80 dans le conteneur
EXPOSE 80









